# Generated by Django 4.1 on 2025-11-13 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstruturaSintatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome da Estrutura')),
                ('descricao', models.TextField(help_text='Definição da estrutura sintática.', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Estrutura Sintática',
                'verbose_name_plural': 'Estruturas Sintáticas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SinalDePontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinal_grafico', models.CharField(help_text="O caractere gráfico (ex: ',', ';', '—')", max_length=10, unique=True, verbose_name='Sinal Gráfico')),
                ('nome', models.CharField(help_text="O nome por extenso (ex: 'Vírgula')", max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(help_text='Descrição geral do sinal.', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Sinal de Pontuação',
                'verbose_name_plural': 'Sinais de Pontuação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MapeamentoFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao_gramatical', models.CharField(help_text="A função exata (ex: 'Isolar', 'Separar', 'Indicar')", max_length=255, verbose_name='Função Gramatical')),
                ('exemplo_de_uso', models.TextField(verbose_name='Exemplo de Uso')),
                ('observacoes', models.TextField(blank=True, help_text='Regras de exceção, notas de estilo ou usos alternativos.', null=True, verbose_name='Observações')),
                ('estrutura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mapeamentos', to='gramatica.estruturasintatica', verbose_name='Estrutura Sintática')),
                ('sinal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mapeamentos', to='gramatica.sinaldepontuacao', verbose_name='Sinal de Pontuação')),
            ],
            options={
                'verbose_name': 'Mapeamento de Função',
                'verbose_name_plural': 'Mapeamentos de Funções',
                'ordering': ['sinal', 'estrutura'],
            },
        ),
        migrations.AddConstraint(
            model_name='mapeamentofuncao',
            constraint=models.UniqueConstraint(fields=('sinal', 'estrutura', 'funcao_gramatical'), name='regra_unica_constraint'),
        ),
    ]
